# Чтобы openwakeword.train не падал на импорте generate_samples
piper_sample_generator_path: "external/piper-sample-generator"
piper_model_path: ""   # не используется без --generate_clips

target_phrase:
  - "Бивис"

custom_negative_phrases: []

# Пути должны существовать, даже если пустые
rir_paths:
  - "data/rir"
background_paths:
  - "data/background"
background_paths_duplication_rate:
  - 1

# Эти поля можно оставить как есть
n_samples: 0
n_samples_val: 0
tts_batch_size: 1

augmentation_batch_size: 16
augmentation_rounds: 1

model_name: "agent"
output_dir: "models"
model_type: "dnn"
layer_size: 128

steps: 2000
batch_n_per_class: 16
max_negative_weight: 3.0
target_false_positives_per_hour: 0.2

feature_data_files: {}
false_positive_validation_data_path: null
